spring:
  application:
    name: TranslateMe-API
    version: 1.0

  output:
    ansi:
      enabled: ALWAYS

  gemini:
    api_key: ${API_KEY}

  main:
    banner-mode: OFF

  datasource:
    url: jdbc:h2:mem:translateme_db
    username: sa
    password:

  jpa:
    database: H2
    properties:
      hibernate:
        format_sql: true
    show-sql: false



